### ISSUE TITLE
Merge The Given 3 Folders in VS Code Folder 

### ISSUE THREAD

**Issue by AnshSinghSonkhia** [AnshSinghSonkhia/Coding-Keyboard-Shortcuts#100]
## Smartly copy the code of the below 3 folders:
- [10 VS Code Shortcuts for Faster Coding.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/10%20VS%20Code%20Shortcuts%20for%20Faster%20Coding.md)
- [5 Useful VSCode shortcuts to improve your coding speed.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/5%20Useful%20VSCode%20shortcuts%20to%20improve%20your%20coding%20speed.md)
- [VsCode_most_useful_shortcut.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/VsCode_most_useful_shortcut.md)

## Paste them Smartly into [VS Code Shortcuts.md](https://github.com/AnshSinghSonkhia/Coding-Keyboard-Shortcuts/blob/main/VS%20Code%20Shortcuts.md) folder.

**Comment by AaryanSingh0017** [comment]
Plz assign this to me?

**Comment by Naman-X15** [comment]
hey @AnshSinghSonkhia I have merged them in a proper way and opened a pull request kindly check.

**Comment by AnshSinghSonkhia** [comment]
Thanks, @Naman-X15 for solving this issue with PR #102.

**Comment by AnshSinghSonkhia** [comment]
**Sorry** @AaryanSingh0017, This issue has been solved.
Check out the other issues of this Repository.
Or create an issue on your own, then If I would feel it good, I'll Assign it to you.

For Example, you can raise an issue of some other programming code editor IDE softwares' Shortcuts, which are not available in this repo.

**Comment by AnshSinghSonkhia** [comment]
Hey @AaryanSingh0017,
**Check Issue #105, it's for you.**
