### ISSUE TITLE
 more VS code shortcuts 

### ISSUE THREAD

**Issue by Aman0786-git** [AnshSinghSonkhia/Coding-Keyboard-Shortcuts#73]
I want to add more VS Code Shorcuts .Can you please assign me

**Comment by RachitGarg-12** [comment]
Hey , i would like to contribute to this issue, can you please assign me this.

**Comment by PandeyMritunjay** [comment]
Let me *CONTRIBUTE* in this Repo By adding More important and Valuable Shortcuts of VS Code as Well as for Online Compiler.
