### ISSUE TITLE
Format Kali-Linux Shortcuts.md

### ISSUE THREAD

**Issue by AnshSinghSonkhia** [AnshSinghSonkhia/Coding-Keyboard-Shortcuts#89]
Arrange it in bullet points or in a table.

**Comment by piyush-sri** [comment]
I would like to work on this issue please assign it to me

**Comment by kmartin62** [comment]
I can take it as well

**Comment by kmartin62** [comment]
@piyush-sri wanna split up? You can do the general shortcuts and improve them in a more visible way while I can do the others.

**Comment by piyush-sri** [comment]
> @piyush-sri wanna split up? You can do the general shortcuts and improve them in a more visible way while I can do the others.

I already arranged the shortcuts in tabular format just center align them.

**Comment by kmartin62** [comment]
which branch?

**Comment by kmartin62** [comment]
> > @piyush-sri wanna split up? You can do the general shortcuts and improve them in a more visible way while I can do the others.
> 
> I already arranged the shortcuts in tabular format just center align them.

You added it as html table, I think that there's an easier way to do it with Markdown.

**Comment by AnshSinghSonkhia** [comment]
> > > @piyush-sri wanna split up? You can do the general shortcuts and improve them in a more visible way while I can do the others.
> > 
> > 
> > I already arranged the shortcuts in tabular format just center align them.
> 
> You added it as html table, I think that there's an easier way to do it with Markdown.

@kmartin62, You can change the bullet points under the General Section into the table. & raise a PR.

**Comment by AnshSinghSonkhia** [comment]
This Issue is solved!

Thanks to @kmartin62 & @piyush-sri.
